@startuml
title Singleton en C con tipo opaco
package "logger.h (lo que ve main.c)" {
  class Logger <<tipo incompleto>>
  class "funciones publicas" as API {
    logger_instancia() : Logger*
    logger_log(Logger*, mensaje)
    logger_cuenta(Logger*) : int
  }
}
package "logger.c (oculto)" {
  class "struct Logger" as Impl {
    log_count : int
  }
  class "static Logger instancia" as Var
}
API ..> Logger
Impl ..|> Logger : define
Var --> Impl
@enduml
