@startuml
!theme toy
class ConfiguracionManager {
  - static _instancia : ConfiguracionManager
  - ConfiguracionManager()
  + static GetInstancia() : ConfiguracionManager
  + Tema : String
  + MostrarConfiguracion() : void
}
@enduml
